<?php
require_once dirname(__FILE__) . '/bootstrap.php';
require_once dirname(__FILE__) . '/web/layouts.php';

// DO NOT EDIT THIS FILE TO CHANGE DEFAULT PAGE
/**
 * This file is here to act as url router. To edit actual web pages
 * check /web folder. If you want a different global url behaviour 
 * then you should it here.
 */

// Check for direct script call and redirect
if (!isset($_SERVER['PATH_INFO']))
    Net_HTTP_Response::redirect($_SERVER['SCRIPT_NAME'] . '/');

// Special handling for special urls 
Stupid::add_rule(create_function('', 'require(\'web/login.php\');'),
	array('type' => 'url_path', 'chunk[-1]' => '/\+login/')
);
Stupid::add_rule(create_function('', 'require(\'web/login.php\');'),
	array('type' => 'url_path', 'chunk[-1]' => '/\+logout/')
);
Stupid::add_rule(create_function('', 'require(\'web/home.php\');'),
	array('type' => 'url_path', 'path' => '/^\/$/')
);

// Include all sub directories under /web
function is_valid_sub($sub)
{
    return is_file(dirname(__FILE__) . "/web/sub/$sub.php");
}

function include_sub($sub)
{
    require dirname(__FILE__)  . "/web/sub/$sub.php";
}

Stupid::add_rule('include_sub',
	array('type' => 'url_path', 'chunk[1]' => '/^([\w]+)$/'),
	array('type' => 'func', 'func' => 'is_valid_sub')
);

Stupid::set_default_action(create_function('', 'require(dirname(__FILE__) . "/web/not_found.php");'));
Stupid::chain_reaction();

?>
